server:
  port: 8080

spring:
  application:
    name: reportservice

  datasource:
    url: jdbc:postgresql://localhost:5433/reportservice
    username: postgresql
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

report:
  processing:
    timeout-ms: 60000